# Your server name, it will be displayed in the ReplayMod
serverName: Example.net

# If true, some memory will be saved, but may lead to lags.
writeDirectly: false

# Recording options
record:
  chat: true
  scoreboard: true
  title: false