main: ${project.groupId}.${project.artifactId}.${project.name}
name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ImNowAPro
depend: [ProtocolLib]
load: STARTUP
api-version: 1.15