main: ${project.groupId}.${project.artifactId}.${project.name}
name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ImNowAPro
depend: [ProtocolLib]
load: STARTUP
api-version: 1.15

commands:
  replay:
    permission: proreplay.command
    description: Main-command of ${project.name}.

permissions:
  proreplay.*:
    description: Allows you to use all commands.
    children:
      proreplay.command: true
  proreplay.command:
    description: Allows you to use the main-command of ${project.name}.
    default: true